Repository stbensonimoh/hbbafrica-volunteer, pull requests merged in 2019-09, with the labels that each got.

#1 Create Front End of Volunteer App
  README.md
  favicon.ico
  images/hbb_logo.jpg
  index.html
  scripts/main.js
  styles/main.css
Labels: enhancement

#2 Fix display bug caused by media queries
  styles/main.css
Labels: bug

#3 Minor bug fixes
  index.html
  scripts/main.js
  styles/main.css
Labels: bug, enhancement

#4 Exciting changes
  index.html
  styles/main.css
Labels: bug, enhancement

#6 Change the Title of the Form
  index.html
  styles/main.css
Labels: enhancement
